### ISSUE TITLE
macOS: Read-only file system

### ISSUE THREAD

**Issue by bencevans** [termius/termius-cli#177]
* Termius CLI Version `1.2.15.`
* OS `macOS Big Sur 11.3.1.`

Running `termius pull` appears to be having issues in writing to `/files`, inhibiting the pull. New to macOS, so I may be missing something, happy to try any suggestions a report back. I installed with `brew install termius`.

```
$ termius pull
Password:
[Errno 30] Read-only file system: '/files'
```

**Comment by bencevans** [comment]
In case of further use (verbose and debug mode enabled):

```
termius init -v --debug
Initializing Termius CLI...

Please enter your Termius credentials

Username: [redacted]
Password:
Starting new HTTPS connection (1): api.termius.com:443
https://api.termius.com:443 "POST /api/v3.1/login/ HTTP/1.1" 200 487

Signed in successfully

Collecting data from the Termius Cloud...
Starting new HTTPS connection (1): api.termius.com:443
https://api.termius.com:443 "POST /api/v3.1/login/ HTTP/1.1" 200 487
Starting new HTTPS connection (1): api.termius.com:443
https://api.termius.com:443 "GET /api/v2/setting/mobile/ HTTP/1.1" 200 577
Starting new HTTPS connection (1): api.termius.com:443
https://api.termius.com:443 "GET /api/v3/terminal/bulk/ HTTP/1.1" 200 80902
[Errno 30] Read-only file system: '/files'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/cliff/command.py", line 97, in run
    return self.take_action(parsed_args) or 0
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/handlers/init.py", line 75, in take_action
    self.pull(namespace)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/handlers/init.py", line 50, in pull
    command.take_action(parsed_args)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/cloud/commands.py", line 53, in take_action
    self.process_sync(controller)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/cloud/commands.py", line 91, in process_sync
    api_controller.get_bulk()
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/cloud/client/controllers.py", line 60, in get_bulk
    model = self._get(mapped)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/cloud/client/controllers.py", line 109, in _get
    model = transformer.to_model(response)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/cloud/client/transformers/many.py", line 106, in to_model
    saved, to_delete = self.to_model_child_list(
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/cloud/client/transformers/many.py", line 164, in to_model_child_list
    child_model = transformer.to_model(i)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/cloud/client/transformers/single.py", line 205, in to_model
    return self.storage.save(descrypted_model)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/core/storage/__init__.py", line 91, in save
    saved_model = self.update(model)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/core/storage/__init__.py", line 122, in update
    post_update_instance.send(
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/core/subscribers.py", line 15, in store_ssh_key
    path.parent.mkdir(parents=True)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/pathlib2/__init__.py", line 1544, in mkdir
    _try_except_filenotfounderror(_try_func, _exc_func)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/pathlib2/__init__.py", line 108, in _try_except_filenotfounderror
    try_func()
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/pathlib2/__init__.py", line 1535, in _try_func
    self._accessor.mkdir(self, mode)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/pathlib2/__init__.py", line 585, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [Errno 30] Read-only file system: '/files'
Traceback (most recent call last):
  File "/opt/homebrew/bin/termius", line 33, in <module>
    sys.exit(load_entry_point('termius==1.2.15', 'console_scripts', 'termius')())
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/main.py", line 26, in main
    return app.run(argv or sys.argv[1:])
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/cliff/app.py", line 279, in run
    result = self.run_subcommand(remainder)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/cliff/command.py", line 97, in run
    return self.take_action(parsed_args) or 0
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/handlers/init.py", line 75, in take_action
    self.pull(namespace)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/handlers/init.py", line 50, in pull
    command.take_action(parsed_args)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/cloud/commands.py", line 53, in take_action
    self.process_sync(controller)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/cloud/commands.py", line 91, in process_sync
    api_controller.get_bulk()
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/cloud/client/controllers.py", line 60, in get_bulk
    model = self._get(mapped)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/cloud/client/controllers.py", line 109, in _get
    model = transformer.to_model(response)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/cloud/client/transformers/many.py", line 106, in to_model
    saved, to_delete = self.to_model_child_list(
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/cloud/client/transformers/many.py", line 164, in to_model_child_list
    child_model = transformer.to_model(i)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/cloud/client/transformers/single.py", line 205, in to_model
    return self.storage.save(descrypted_model)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/core/storage/__init__.py", line 91, in save
    saved_model = self.update(model)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/core/storage/__init__.py", line 122, in update
    post_update_instance.send(
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/termius/core/subscribers.py", line 15, in store_ssh_key
    path.parent.mkdir(parents=True)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/pathlib2/__init__.py", line 1544, in mkdir
    _try_except_filenotfounderror(_try_func, _exc_func)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/pathlib2/__init__.py", line 108, in _try_except_filenotfounderror
    try_func()
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/pathlib2/__init__.py", line 1535, in _try_func
    self._accessor.mkdir(self, mode)
  File "/opt/homebrew/Cellar/termius/1.2.15_1/libexec/lib/python3.9/site-packages/pathlib2/__init__.py", line 585, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [Errno 30] Read-only file system: '/files'
```
