### ISSUE TITLE
Error! 'location'

### ISSUE THREAD

**Issue by madAndroid** [termius/termius-cli#7]
Hi, firstly, great product :)

Seeing this when running `serverauditor export`:

```
You may confirm this list (press 'Enter'), add (enter '+') or remove (enter its number) host:
OK!
Getting full information...
Success!
Creating keys and connections...
Error! 'location'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/serverauditor_sshconfig/core/application.py", line 32, in wrapped
    func(self)
  File "/Library/Python/2.7/site-packages/serverauditor_sshconfig/sa_export.py", line 173, in _create_keys_and_connections
    self._api.create_keys_and_connections(self._full_local_hosts, self._sa_username, self._sa_auth_key)
  File "/Library/Python/2.7/site-packages/serverauditor_sshconfig/core/api.py", line 70, in create_keys_and_connections
    key_numbers.append(int(response.headers['Location'].rstrip('/').rsplit('/', 1)[-1]))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/rfc822.py", line 388, in __getitem__
    return self.dict[name.lower()]
KeyError: 'location'
```

Operating System: `Mac OSX - 10.10.4`
Python: `Python 2.7.6`

**Comment by EvgeneOskin** [comment]
It was fixed. Sorry for the late reply (really late reply).
